package model.pojo;
// Generated May 15, 2015 6:57:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Buses generated by hbm2java
 */
public class Buses  implements java.io.Serializable {


     private BusesId id;
     private Integer fare;

    public Buses() {
    }

	
    public Buses(BusesId id) {
        this.id = id;
    }
    public Buses(BusesId id, Integer fare) {
       this.id = id;
       this.fare = fare;
    }
   
    public BusesId getId() {
        return this.id;
    }
    
    public void setId(BusesId id) {
        this.id = id;
    }
    public Integer getFare() {
        return this.fare;
    }
    
    public void setFare(Integer fare) {
        this.fare = fare;
    }




}


