package model.pojo;
// Generated May 15, 2015 6:57:35 PM by Hibernate Tools 3.2.1.GA



/**
 * DistancesId generated by hbm2java
 */
public class DistancesId  implements java.io.Serializable {


     private String placeA;
     private String placeB;

    public DistancesId() {
    }

    public DistancesId(String placeA, String placeB) {
       this.placeA = placeA;
       this.placeB = placeB;
    }
   
    public String getPlaceA() {
        return this.placeA;
    }
    
    public void setPlaceA(String placeA) {
        this.placeA = placeA;
    }
    public String getPlaceB() {
        return this.placeB;
    }
    
    public void setPlaceB(String placeB) {
        this.placeB = placeB;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DistancesId) ) return false;
		 DistancesId castOther = ( DistancesId ) other; 
         
		 return ( (this.getPlaceA()==castOther.getPlaceA()) || ( this.getPlaceA()!=null && castOther.getPlaceA()!=null && this.getPlaceA().equals(castOther.getPlaceA()) ) )
 && ( (this.getPlaceB()==castOther.getPlaceB()) || ( this.getPlaceB()!=null && castOther.getPlaceB()!=null && this.getPlaceB().equals(castOther.getPlaceB()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPlaceA() == null ? 0 : this.getPlaceA().hashCode() );
         result = 37 * result + ( getPlaceB() == null ? 0 : this.getPlaceB().hashCode() );
         return result;
   }   


}


