package model.pojo;
// Generated May 15, 2015 6:57:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Distances generated by hbm2java
 */
public class Distances  implements java.io.Serializable {


     private DistancesId id;
     private Integer distance;

    public Distances() {
    }

	
    public Distances(DistancesId id) {
        this.id = id;
    }
    public Distances(DistancesId id, Integer distance) {
       this.id = id;
       this.distance = distance;
    }
   
    public DistancesId getId() {
        return this.id;
    }
    
    public void setId(DistancesId id) {
        this.id = id;
    }
    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }




}


