package model.pojo;
// Generated May 15, 2015 6:57:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Taxis generated by hbm2java
 */
public class Taxis  implements java.io.Serializable {


     private String regNo;
     private String driverName;
     private String contactNo;
     private String taxiModel;
     private String location;

    public Taxis() {
    }

	
    public Taxis(String regNo) {
        this.regNo = regNo;
    }
    public Taxis(String regNo, String driverName, String contactNo, String taxiModel, String location) {
       this.regNo = regNo;
       this.driverName = driverName;
       this.contactNo = contactNo;
       this.taxiModel = taxiModel;
       this.location = location;
    }
   
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getTaxiModel() {
        return this.taxiModel;
    }
    
    public void setTaxiModel(String taxiModel) {
        this.taxiModel = taxiModel;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


